version: "3"
services:

  redis:
    container_name: redis
    image: redis
    environment:
      REDIS_PORT: 6379

  auth:
    container_name: auth
    build:
      context: ./auth
    environment:
      REDIS_HOST: redis
      REDIS_PORT:  6379
